added the sauce function
ShannonHolgate/BuildASub pull request #5
Opened 2016-10-14 13:03 UTC by lburns660

2016-10-14 13:13 UTC, John-Doherty01 requested changes

2016-10-14 13:13 UTC, John-Doherty01 commented on src/BuildASub.java
> +            System.out.println("Your chosen sauce is:" + sauce);
Calum and Maria are handling outputs, please remove sauce output line

2016-10-14 13:13 UTC, John-Doherty01 commented on src/BuildASub.java
Remove excess spacing

2016-10-14 13:13 UTC, John-Doherty01 commented on src/BuildASub.java
> +        if (sauceOption.equalsIgnoreCase("yes")) {
Allow for letters y/n rather than yes/no

2016-10-14 13:13 UTC, John-Doherty01 commented on src/BuildASub.java
> +                    chooseSauce();
Other possibility instead of recursion is the use of exceptions

2016-10-17 08:56 UTC, lburns660 commented on src/BuildASub.java
hey John hook me up

2016-10-17 08:56 UTC, John-Doherty01 approved these changes

2016-10-17 08:57 UTC, merged